### ISSUE TITLE
Error: Cannot find module './parse.coffee'

### ISSUE THREAD

**Issue by didjeridou** [AbhinavMadahar/Easypedia#1]
Hi there, 

I'm using Easypedia in Meteor and I'm getting the following error:

```
Error: Cannot find module './parse.coffee'
```

Any ideas?

**Comment by AbhinavMadahar** [comment]
I think I have a solution

**Comment by AbhinavMadahar** [comment]
Version 1.6.11 should have fixed this. Can you confirm that it works for you? It does for me

**Comment by didjeridou** [comment]
Confirmed, works now. Thanks!!

**Comment by AbhinavMadahar** [comment]
Thanks for reporting it
